/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
import java.awt.Color;

public class LayoutKalkulator extends javax.swing.JFrame {

    /**
     * Creates new form LayoutKalkulator
     */
    String angka=""; //
    double jumlah, angka1, angka2;
    int pilih;
    
    public LayoutKalkulator() {
        initComponents();
        Display.setBackground(new Color(0,0,0,0));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Display = new javax.swing.JTextField();
        ButtonHasil = new javax.swing.JButton();
        ButtonClear = new javax.swing.JButton();
        ButtonTambah = new javax.swing.JButton();
        ButtonKurang = new javax.swing.JButton();
        ButtonKali = new javax.swing.JButton();
        ButtonPlusMinus = new javax.swing.JButton();
        Button9 = new javax.swing.JButton();
        Button8 = new javax.swing.JButton();
        Button7 = new javax.swing.JButton();
        Button6 = new javax.swing.JButton();
        Button5 = new javax.swing.JButton();
        Button4 = new javax.swing.JButton();
        Button1 = new javax.swing.JButton();
        Button2 = new javax.swing.JButton();
        Button3 = new javax.swing.JButton();
        ButtonKoma = new javax.swing.JButton();
        ButtonDelete = new javax.swing.JButton();
        Button0 = new javax.swing.JButton();
        ButtonBagi1 = new javax.swing.JButton();
        BACKGROUND = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setMinimumSize(new java.awt.Dimension(400, 550));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Display.setEditable(false);
        Display.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        Display.setForeground(new java.awt.Color(255, 255, 255));
        Display.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Display.setBorder(null);
        Display.setCaretColor(new java.awt.Color(255, 255, 255));
        Display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayActionPerformed(evt);
            }
        });
        getContentPane().add(Display, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 140));

        ButtonHasil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/V3/HASIL.png"))); // NOI18N
        ButtonHasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHasilActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonHasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 100, 140));

        ButtonClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/V3/CLEAR.png"))); // NOI18N
        ButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClearActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 100, 70));

        ButtonTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/V3/TAMBAH.png"))); // NOI18N
        ButtonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTambahActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 100, 70));

        ButtonKurang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/V3/KURANG.png"))); // NOI18N
        ButtonKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKurangActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonKurang, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 100, 70));

        ButtonKali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/V3/KALI.png"))); // NOI18N
        ButtonKali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKaliActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonKali, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 100, 70));

        ButtonPlusMinus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/V3/PLUS MINES.png"))); // NOI18N
        ButtonPlusMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPlusMinusActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonPlusMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 100, 70));

        Button9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/V3/9.png"))); // NOI18N
        Button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button9ActionPerformed(evt);
            }
        });
        getContentPane().add(Button9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 100, 70));

        Button8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/V3/8.png"))); // NOI18N
        Button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button8ActionPerformed(evt);
            }
        });
        getContentPane().add(Button8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 100, 70));

        Button7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/V3/7.png"))); // NOI18N
        Button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button7ActionPerformed(evt);
            }
        });
        getContentPane().add(Button7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 237, 100, 70));

        Button6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/V3/6.png"))); // NOI18N
        Button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button6ActionPerformed(evt);
            }
        });
        getContentPane().add(Button6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 317, 100, 70));

        Button5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/V3/5.png"))); // NOI18N
        Button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button5ActionPerformed(evt);
            }
        });
        getContentPane().add(Button5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 317, 100, 70));

        Button4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/V3/4.png"))); // NOI18N
        Button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button4ActionPerformed(evt);
            }
        });
        getContentPane().add(Button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 317, 100, 70));

        Button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/V3/1.png"))); // NOI18N
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });
        getContentPane().add(Button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 100, 77));

        Button2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/V3/2.png"))); // NOI18N
        Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button2ActionPerformed(evt);
            }
        });
        getContentPane().add(Button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 100, 77));

        Button3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/V3/3.png"))); // NOI18N
        Button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button3ActionPerformed(evt);
            }
        });
        getContentPane().add(Button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 100, 77));

        ButtonKoma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/V3/KOMA.png"))); // NOI18N
        ButtonKoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKomaActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonKoma, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 100, 70));

        ButtonDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/V3/DELETE.png"))); // NOI18N
        ButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 317, 100, 70));

        Button0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/V3/0.png"))); // NOI18N
        Button0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button0ActionPerformed(evt);
            }
        });
        getContentPane().add(Button0, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, 100, 70));

        ButtonBagi1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/V3/BAGI.png"))); // NOI18N
        ButtonBagi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBagi1ActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonBagi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 100, 70));

        BACKGROUND.setIcon(new javax.swing.ImageIcon(getClass().getResource("/V3/Calculator BG.png"))); // NOI18N
        getContentPane().add(BACKGROUND, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonHasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHasilActionPerformed
        equal();
// TODO add your handling code here:
//        switch(pilih){
//        case 1 :
//            angka2 = Double.parseDouble(angka);
//            angka1 = angka1+angka2;
//            angka = Double.toString(jumlah);
//            Display.setText(angka);
//            break;
//        case 2 :
//            angka2 = Double.parseDouble(angka);
//            jumlah = angka1-angka2;
//            angka = Double.toString(jumlah);
//            Display.setText(angka);
//            break;
//        case 3 :
//            angka2 = Double.parseDouble(angka);
//            jumlah = angka1*angka2;
//            angka = Double.toString(jumlah);
//            Display.setText(angka);
//            break;
//        case 4 :
//            angka2 = Double.parseDouble(angka);
//            jumlah = angka1/angka2;
//            angka = Double.toString(jumlah);
//            Display.setText(angka);
//            break;
//        default:
//            break;
//    }
    }//GEN-LAST:event_ButtonHasilActionPerformed

    public void equal(){
        switch(pilih){
        case 1 :
            angka2 = Double.parseDouble(angka);
            angka1 = angka1+angka2;
            angka = Double.toString(angka1);
            Display.setText(angka);
            break;
        case 2 :
            angka2 = Double.parseDouble(angka);
            angka1 = angka1-angka2;
            angka = Double.toString(angka1);
            Display.setText(angka);
            break;
        case 3 :
            angka2 = Double.parseDouble(angka);
            angka1 = angka1*angka2;
            angka = Double.toString(angka1);
            Display.setText(angka);
            break;
        case 4 :
            angka2 = Double.parseDouble(angka);
            angka1 = angka1/angka2;
            angka = Double.toString(angka1);
            Display.setText(angka);
            break;
        default:
            break;
    }
    pilih=0;
    }
    private void ButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonClearActionPerformed
        // TODO add your handling code here:
        Display.setText("");
        angka1 = 0.0;
        angka2 = 0.0;
        jumlah = 0.0;
        angka = "";
    }//GEN-LAST:event_ButtonClearActionPerformed

    private void ButtonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTambahActionPerformed
        // TODO add your handling code here:
        if(angka1==0){
            angka1 = Double.parseDouble(angka);
            Display.setText("+");
            angka = "";
            pilih = 1;
        }
        else if(angka1!=0){
            equal();
            angka = "";
            pilih = 1;
        }
    }//GEN-LAST:event_ButtonTambahActionPerformed

    private void ButtonKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKurangActionPerformed
        // TODO add your handling code here:
        if(angka1==0){
            angka1 = Double.parseDouble(angka);
            Display.setText("-");
            angka = "";
            pilih = 2;
        }
        else if(angka1!=0){
            equal();
            angka = "";
            pilih = 2;
        }
    }//GEN-LAST:event_ButtonKurangActionPerformed

        
    private void ButtonKaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKaliActionPerformed
        // TODO add your handling code here:
        if(angka1==0){
            angka1 = Double.parseDouble(angka);
            Display.setText("X");
            angka = "";
            pilih = 3;
        }
        else if(angka1!=0){
            equal();
            angka = "";
            pilih = 3;
        }
    }//GEN-LAST:event_ButtonKaliActionPerformed

    private void ButtonPlusMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPlusMinusActionPerformed
        // TODO add your handling code here:
        double text = Double.parseDouble(Display.getText());
        text=text*(-1);
        angka=Double.toString(text);
        Display.setText(angka);
    }//GEN-LAST:event_ButtonPlusMinusActionPerformed

    private void Button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button9ActionPerformed
        // TODO add your handling code here:
        angka += "9";
        Display.setText(angka);
    }//GEN-LAST:event_Button9ActionPerformed

    private void Button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button8ActionPerformed
        // TODO add your handling code here:
        angka += "8";
        Display.setText(angka);
    }//GEN-LAST:event_Button8ActionPerformed

    private void Button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button7ActionPerformed
        // TODO add your handling code here:
        angka += "7";
        Display.setText(angka);
    }//GEN-LAST:event_Button7ActionPerformed

    private void Button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button6ActionPerformed
        // TODO add your handling code here:
        angka += "6";
        Display.setText(angka);
    }//GEN-LAST:event_Button6ActionPerformed

    private void Button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button5ActionPerformed
        // TODO add your handling code here:
        angka += "5";
        Display.setText(angka);
    }//GEN-LAST:event_Button5ActionPerformed

    private void Button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button4ActionPerformed
        // TODO add your handling code here:
        angka += "4";
        Display.setText(angka);
    }//GEN-LAST:event_Button4ActionPerformed

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
        // TODO add your handling code here:
        angka += "1";
        Display.setText(angka);
    }//GEN-LAST:event_Button1ActionPerformed

    private void Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button2ActionPerformed
        // TODO add your handling code here:
        angka += "2";
        Display.setText(angka);
    }//GEN-LAST:event_Button2ActionPerformed

    private void Button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button3ActionPerformed
        // TODO add your handling code here:
        angka += "3";
        Display.setText(angka);
    }//GEN-LAST:event_Button3ActionPerformed

    private void ButtonKomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKomaActionPerformed
        // TODO add your handling code here:
        angka += ".";
        Display.setText(angka);
    }//GEN-LAST:event_ButtonKomaActionPerformed

    private void ButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeleteActionPerformed
        // TODO add your handling code here:
        int length = Display.getText().length();
        int number = Display.getText().length()-1;
        String hDelete;
        if (length>0){
            StringBuilder delete = new StringBuilder(Display.getText());
            delete.deleteCharAt(number);
            hDelete = delete.toString();
            Display.setText(hDelete);
    }
    }//GEN-LAST:event_ButtonDeleteActionPerformed

    private void Button0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button0ActionPerformed
        // TODO add your handling code here:
        angka += "0";
        Display.setText(angka);
    }//GEN-LAST:event_Button0ActionPerformed

    private void DisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DisplayActionPerformed

    private void ButtonBagi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBagi1ActionPerformed
        // TODO add your handling code here:
        if(angka1==0){
            angka1 = Double.parseDouble(angka);
            Display.setText("/");
            angka = "";
            pilih = 4;
        }
        else if(angka1!=0){
            equal();
            angka = "";
            pilih = 4;
        }
    }//GEN-LAST:event_ButtonBagi1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LayoutKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LayoutKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LayoutKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LayoutKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LayoutKalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BACKGROUND;
    private javax.swing.JButton Button0;
    private javax.swing.JButton Button1;
    private javax.swing.JButton Button2;
    private javax.swing.JButton Button3;
    private javax.swing.JButton Button4;
    private javax.swing.JButton Button5;
    private javax.swing.JButton Button6;
    private javax.swing.JButton Button7;
    private javax.swing.JButton Button8;
    private javax.swing.JButton Button9;
    private javax.swing.JButton ButtonBagi1;
    private javax.swing.JButton ButtonClear;
    private javax.swing.JButton ButtonDelete;
    private javax.swing.JButton ButtonHasil;
    private javax.swing.JButton ButtonKali;
    private javax.swing.JButton ButtonKoma;
    private javax.swing.JButton ButtonKurang;
    private javax.swing.JButton ButtonPlusMinus;
    private javax.swing.JButton ButtonTambah;
    private javax.swing.JTextField Display;
    // End of variables declaration//GEN-END:variables
}
